version: "3"
services:
  webserver:
    image: nginx:latest
    logging:
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "100m"
    working_dir: /application
    container_name: nginx-gunicorn-webserver      
    volumes:
        - ../../../www:/www
        - ../../../script/:/script/
        - ../../../config/web-server/nginx/gunicorn/conf.d/:/etc/nginx/conf.d/
        - ../../../config/web-server/nginx/gunicorn/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
        - ../../../config/web-server/nginx/gunicorn/proxy_params/proxy_params:/etc/nginx/proxy_params
        - ../../../ssl/:/ssl/
        - ../../../log:/log
    ports:
        - "80:80"
        - "443:443"
    environment:
        TZ: "Asia/Seoul"
    restart: always

  gunicorn-app:
    build: ../../../docker/gunicorn/
    logging:
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "100m"
    working_dir: /application
    container_name: gunicorn-app    
    volumes:
        - ../../../www:/www
        - ../../../log:/log        
    command:
        - /tmp/run.sh    
    environment:
        TZ: "Asia/Seoul"
    restart: always

  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: "test1324"
    
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
        - 8080:80
    environment:
        - PMA_ARBITRARY=1      
        #Provides a form to directly enter the server information to connect using the login screen.
        #- PMA_HOST=mariadb
        #Specify the server to connect to. (You cannot select a server to connect to on the login screen)
    depends_on:
        - mariadb
